name: firestorex
description: Firestore Extensions
version: 0.0.1
homepage: mehmetesen.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ">=3.0.0 <4.0.0"
  json_annotation: ">=4.0.0 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  fake_cloud_firestore: ^1.2.0
  mockito: 5.1.0
  rand:
    git:
      url: https://github.com/esenmx/rand
      ref: main
  test_utils:
    git:
      url: https://github.com/esenmx/test_utils
      ref: main

flutter: