name: firecraft
description: The ultimate companion for building Firestore applications with Flutter
version: 0.0.1
homepage: mehmetesen.com

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ">=4.0.0 <5.0.0"
  json_annotation: ">=4.0.0 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  fake_cloud_firestore: ^2.0.1
  mockito: ^5.3.0
  fake_async: ^1.3.1
  rand:
    git:
      url: https://github.com/esenmx/rand
      ref: main
  test_utils:
    git:
      url: https://github.com/esenmx/test_utils
      ref: main
