name: firestorex
description: Firestore Extensions
version: 0.0.1
homepage: mehmetesen.com

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ">=3.0.0 <4.0.0"
  rxdart: ">=0.27.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  fake_cloud_firestore: ^1.2.0
  mockito: ^5.0.17

flutter: