name: firecraft
description: The ultimate companion for building Firestore applications with Flutter
version: 0.0.1
homepage: mehmetesen.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  fake_cloud_firestore:
  mockito:
  fake_async:
  rand:
    git:
      url: https://github.com/esenmx/rand
      ref: main
  test_utils:
    git:
      url: https://github.com/esenmx/test_utils
      ref: main
