name: firestorex
description: Firestore Extensions
version: 0.0.1
homepage: mehmetesen.com

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ">=3.0.0 <4.0.0"
  async: ^2.8.2
  json_annotation: ">=4.0.0 <5.0.0"
  dashx:
    git:
      url: https://github.com/esenmx/dashx
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  fake_cloud_firestore: ^1.2.0
  test_utils:
    git:
      url: https://github.com/esenmx/test_utils
      ref: main

flutter: