name: firecraft
description: The ultimate companion for building Firestore applications with Flutter
version: 0.0.1
homepage: mehmetesen.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore:
  flutter:
    sdk: flutter
  json_annotation:

dev_dependencies:
  fake_async:
  fake_cloud_firestore:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  mockito:
  rand:
  test_utils:
    git:
      url: https://github.com/esenmx/test_utils
      ref: main
